title: Sergio Flores
email: byoigres@gmail.com
description: "Blog personal y curiosidades de todos los días."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://byoigres.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:year/:month/:day/:title/
twitter_username: byoigres
github_username:  byoigres

# Build settings
markdown: kramdown
# theme: minima

#custom attreibutes
disqus_username: byoigres

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - _config_dev.yml
  - CNAME
  - webpack.config.js
  - packages.json
  - node_modules
  - yarn.lock
  - .babelrc
  - .editorconfig
  - .eslintignore
  - .eslintrc
